include(../shared.pri)

HEADERS = \
    inc/Analysis/Analysis.h \
    inc/Analysis/Assembler/Assembler.h \
    inc/Analysis/Solvers/Buckling.h \
    inc/Analysis/Solvers/Dynamic_Linear.h \
    inc/Analysis/Solvers/Dynamic_Nonlinear.h \
    inc/Analysis/Solvers/Minimum.h \
    inc/Analysis/Solvers/Modal.h \
    inc/Analysis/Solvers/Nonlinear.h \
    inc/Analysis/Solvers/Solver.h \
    inc/Analysis/Solvers/Solvers.h \
    inc/Analysis/Solvers/State.h \
    inc/Analysis/Solvers/Static_Linear.h \
    inc/Analysis/Solvers/Static_Nonlinear.h \
    inc/Analysis/Solvers/Time.h \
    inc/Analysis/Solvers/Transient_Linear.h \
    inc/Analysis/Solvers/Transient_Nonlinear.h \
    inc/Analysis/Solvers/Types.h \
    inc/Analysis/Solvers/Watch_Dof.h \
    inc/Analysis/Strategies/Arc_Length_Cylindric.h \
    inc/Analysis/Strategies/Arc_Length_Linear.h \
    inc/Analysis/Strategies/Arc_Length_Spheric.h \
    inc/Analysis/Strategies/Control_Load.h \
    inc/Analysis/Strategies/Control_State.h \
    inc/Analysis/Strategies/Minimal_Norm.h \
    inc/Analysis/Strategies/Orthogonal_Residue.h \
    inc/Analysis/Strategies/Strategies.h \
    inc/Analysis/Strategies/Strategy.h \
    inc/Analysis/Strategies/Types.h \
    inc/Boundary/Boundary.h \
    inc/Boundary/Cases/Load_Case.h \
    inc/Boundary/Dependencies/Dependency.h \
    inc/Boundary/Initials/Initial.h \
    inc/Boundary/Loads/Elements/Element.h \
    inc/Boundary/Loads/Elements/Mechanic/Frame/Axial.h \
    inc/Boundary/Loads/Elements/Mechanic/Frame/Bending.h \
    inc/Boundary/Loads/Elements/Mechanic/Frame/Shear.h \
    inc/Boundary/Loads/Elements/Mechanic/Frame/Torsion.h \
    inc/Boundary/Loads/Elements/Mechanic/Mechanic.h \
    inc/Boundary/Loads/Elements/Mechanic/Plane/Plane.h \
    inc/Boundary/Loads/Elements/Mechanic/Plane/Plane_Edge.h \
    inc/Boundary/Loads/Elements/Mechanic/Plane/Plane_Face.h \
    inc/Boundary/Loads/Elements/Mechanic/Solid/Solid.h \
    inc/Boundary/Loads/Elements/Mechanic/Solid/Solid_Body.h \
    inc/Boundary/Loads/Elements/Mechanic/Solid/Solid_Edge.h \
    inc/Boundary/Loads/Elements/Mechanic/Solid/Solid_Face.h \
    inc/Boundary/Loads/Load.h \
    inc/Boundary/Loads/Loads.h \
    inc/Boundary/Loads/Nodes/Node.h \
    inc/Boundary/Loads/Types.h \
    inc/Boundary/Supports/Support.h \
    inc/Mesh/Cells/Cell.h \
    inc/Mesh/Cells/Cells.h \
    inc/Mesh/Cells/Line/Bar.h \
    inc/Mesh/Cells/Line/Beam.h \
    inc/Mesh/Cells/Line/Line.h \
    inc/Mesh/Cells/Plane/Plane.h \
    inc/Mesh/Cells/Plane/Quad.h \
    inc/Mesh/Cells/Plane/Quad4.h \
    inc/Mesh/Cells/Plane/Quad8.h \
    inc/Mesh/Cells/Plane/Quad9.h \
    inc/Mesh/Cells/Plane/Tri.h \
    inc/Mesh/Cells/Plane/Tri3.h \
    inc/Mesh/Cells/Plane/Tri6.h \
    inc/Mesh/Cells/Types.h \
    inc/Mesh/Cells/Volume/Brick.h \
    inc/Mesh/Cells/Volume/Brick20.h \
    inc/Mesh/Cells/Volume/Brick27.h \
    inc/Mesh/Cells/Volume/Brick8.h \
    inc/Mesh/Cells/Volume/Tetra.h \
    inc/Mesh/Cells/Volume/Tetra10.h \
    inc/Mesh/Cells/Volume/Tetra4.h \
    inc/Mesh/Cells/Volume/Volume.h \
    inc/Mesh/Elements/Element.h \
    inc/Mesh/Elements/Elements.h \
    inc/Mesh/Elements/Heat/Heat.h \
    inc/Mesh/Elements/Mechanic/Frame/Bar.h \
    inc/Mesh/Elements/Mechanic/Frame/Beam2.h \
    inc/Mesh/Elements/Mechanic/Frame/Beam3.h \
    inc/Mesh/Elements/Mechanic/Frame/Cable.h \
    inc/Mesh/Elements/Mechanic/Frame/Frame.h \
    inc/Mesh/Elements/Mechanic/Frame/Rope.h \
    inc/Mesh/Elements/Mechanic/Mechanic.h \
    inc/Mesh/Elements/Mechanic/Plane/Plane.h \
    inc/Mesh/Elements/Mechanic/Solid/Solid.h \
    inc/Mesh/Elements/States.h \
    inc/Mesh/Elements/Types.h \
    inc/Mesh/Joints/Hinge.h \
    inc/Mesh/Joints/Joint.h \
    inc/Mesh/Joints/Joints.h \
    inc/Mesh/Joints/Pinned.h \
    inc/Mesh/Joints/Rigid.h \
    inc/Mesh/Joints/Spherical.h \
    inc/Mesh/Joints/Spring.h \
    inc/Mesh/Joints/States.h \
    inc/Mesh/Joints/Types.h \
    inc/Mesh/Materials/Heat/Heat.h \
    inc/Mesh/Materials/Material.h \
    inc/Mesh/Materials/Materials.h \
    inc/Mesh/Materials/Mechanic/Associative/Associative.h \
    inc/Mesh/Materials/Mechanic/Associative/Concrete.h \
    inc/Mesh/Materials/Mechanic/Associative/Steel.h \
    inc/Mesh/Materials/Mechanic/Mechanic.h \
    inc/Mesh/Materials/Types.h \
    inc/Mesh/Mesh.h \
    inc/Mesh/Nodes/Dofs.h \
    inc/Mesh/Nodes/Node.h \
    inc/Mesh/Points/Heat/Heat.h \
    inc/Mesh/Points/Mechanic/Fiber.h \
    inc/Mesh/Points/Mechanic/Mechanic.h \
    inc/Mesh/Points/Mechanic/Section.h \
    inc/Mesh/Points/Mechanic/States.h \
    inc/Mesh/Points/Point.h \
    inc/Mesh/Points/Points.h \
    inc/Mesh/Points/Types.h \
    inc/Mesh/Sections/Box.h \
    inc/Mesh/Sections/Circle.h \
    inc/Mesh/Sections/Generic.h \
    inc/Mesh/Sections/I.h \
    inc/Mesh/Sections/Rebar.h \
    inc/Mesh/Sections/Rectangle.h \
    inc/Mesh/Sections/Ring.h \
    inc/Mesh/Sections/Section.h \
    inc/Mesh/Sections/Sections.h \
    inc/Mesh/Sections/T.h \
    inc/Mesh/Sections/Types.h \
    inc/Models/Model.h \
    inc/Plot/Colors.h \
    inc/Plot/Gradient.h \
    inc/Plot/Plot.h \
    inc/Plot/Sizes.h \
    inc/Plot/View.h \
    inc/Plot/What.h \
    inc/Topology/Curves/Curve.h \
    inc/Topology/Curves/Line.h \
    inc/Topology/Points/Point.h \
    inc/Topology/Surfaces/Surface.h \
    inc/Topology/Topologies.h \
    inc/Topology/Topology.h \


SOURCES = \
    src/Analysis/Analysis.cpp \
    src/Analysis/Assembler/Assembler.cpp \
    src/Analysis/Solvers/Buckling.cpp \
    src/Analysis/Solvers/Dynamic_Linear.cpp \
    src/Analysis/Solvers/Dynamic_Nonlinear.cpp \
    src/Analysis/Solvers/Minimum.cpp \
    src/Analysis/Solvers/Modal.cpp \
    src/Analysis/Solvers/Nonlinear.cpp \
    src/Analysis/Solvers/Solver.cpp \
    src/Analysis/Solvers/State.cpp \
    src/Analysis/Solvers/Static_Linear.cpp \
    src/Analysis/Solvers/Static_Nonlinear.cpp \
    src/Analysis/Solvers/Time.cpp \
    src/Analysis/Solvers/Transient_Linear.cpp \
    src/Analysis/Solvers/Transient_Nonlinear.cpp \
    src/Analysis/Solvers/Watch_Dof.cpp \
    src/Analysis/Strategies/Arc_Length_Cylindric.cpp \
    src/Analysis/Strategies/Arc_Length_Linear.cpp \
    src/Analysis/Strategies/Arc_Length_Spheric.cpp \
    src/Analysis/Strategies/Control_Load.cpp \
    src/Analysis/Strategies/Control_State.cpp \
    src/Analysis/Strategies/Minimal_Norm.cpp \
    src/Analysis/Strategies/Orthogonal_Residue.cpp \
    src/Analysis/Strategies/Strategy.cpp \
    src/Boundary/Boundary.cpp \
    src/Boundary/Cases/Load_Case.cpp \
    src/Boundary/Dependencies/Dependency.cpp \
    src/Boundary/Initials/Initial.cpp \
    src/Boundary/Loads/Elements/Element.cpp \
    src/Boundary/Loads/Elements/Mechanic/Frame/Axial.cpp \
    src/Boundary/Loads/Elements/Mechanic/Frame/Bending.cpp \
    src/Boundary/Loads/Elements/Mechanic/Frame/Shear.cpp \
    src/Boundary/Loads/Elements/Mechanic/Frame/Torsion.cpp \
    src/Boundary/Loads/Elements/Mechanic/Mechanic.cpp \
    src/Boundary/Loads/Elements/Mechanic/Plane/Plane.cpp \
    src/Boundary/Loads/Elements/Mechanic/Plane/Plane_Edge.cpp \
    src/Boundary/Loads/Elements/Mechanic/Plane/Plane_Face.cpp \
    src/Boundary/Loads/Elements/Mechanic/Solid/Solid.cpp \
    src/Boundary/Loads/Elements/Mechanic/Solid/Solid_Body.cpp \
    src/Boundary/Loads/Elements/Mechanic/Solid/Solid_Edge.cpp \
    src/Boundary/Loads/Elements/Mechanic/Solid/Solid_Face.cpp \
    src/Boundary/Loads/Load.cpp \
    src/Boundary/Loads/Nodes/Node.cpp \
    src/Boundary/Supports/Support.cpp \
    src/Mesh/Cells/Cell.cpp \
    src/Mesh/Cells/Line/Bar.cpp \
    src/Mesh/Cells/Line/Beam.cpp \
    src/Mesh/Cells/Line/Line.cpp \
    src/Mesh/Cells/Plane/Plane.cpp \
    src/Mesh/Cells/Plane/Quad.cpp \
    src/Mesh/Cells/Plane/Quad4.cpp \
    src/Mesh/Cells/Plane/Quad8.cpp \
    src/Mesh/Cells/Plane/Quad9.cpp \
    src/Mesh/Cells/Plane/Tri.cpp \
    src/Mesh/Cells/Plane/Tri3.cpp \
    src/Mesh/Cells/Plane/Tri6.cpp \
    src/Mesh/Cells/Volume/Brick.cpp \
    src/Mesh/Cells/Volume/Brick20.cpp \
    src/Mesh/Cells/Volume/Brick27.cpp \
    src/Mesh/Cells/Volume/Brick8.cpp \
    src/Mesh/Cells/Volume/Tetra.cpp \
    src/Mesh/Cells/Volume/Tetra10.cpp \
    src/Mesh/Cells/Volume/Tetra4.cpp \
    src/Mesh/Cells/Volume/Volume.cpp \
    src/Mesh/Elements/Element.cpp \
    src/Mesh/Elements/Heat/Heat.cpp \
    src/Mesh/Elements/Mechanic/Frame/Bar.cpp \
    src/Mesh/Elements/Mechanic/Frame/Beam2.cpp \
    src/Mesh/Elements/Mechanic/Frame/Beam3.cpp \
    src/Mesh/Elements/Mechanic/Frame/Cable.cpp \
    src/Mesh/Elements/Mechanic/Frame/Frame.cpp \
    src/Mesh/Elements/Mechanic/Frame/Rope.cpp \
    src/Mesh/Elements/Mechanic/Mechanic.cpp \
    src/Mesh/Elements/Mechanic/Plane/Plane.cpp \
    src/Mesh/Elements/Mechanic/Solid/Solid.cpp \
    src/Mesh/Joints/Hinge.cpp \
    src/Mesh/Joints/Joint.cpp \
    src/Mesh/Joints/Pinned.cpp \
    src/Mesh/Joints/Rigid.cpp \
    src/Mesh/Joints/Spherical.cpp \
    src/Mesh/Joints/Spring.cpp \
    src/Mesh/Materials/Heat/Heat.cpp \
    src/Mesh/Materials/Material.cpp \
    src/Mesh/Materials/Mechanic/Associative/Associative.cpp \
    src/Mesh/Materials/Mechanic/Associative/Concrete.cpp \
    src/Mesh/Materials/Mechanic/Associative/Steel.cpp \
    src/Mesh/Materials/Mechanic/Mechanic.cpp \
    src/Mesh/Mesh.cpp \
    src/Mesh/Nodes/Node.cpp \
    src/Mesh/Points/Heat/Heat.cpp \
    src/Mesh/Points/Mechanic/Fiber.cpp \
    src/Mesh/Points/Mechanic/Mechanic.cpp \
    src/Mesh/Points/Mechanic/Section.cpp \
    src/Mesh/Points/Point.cpp \
    src/Mesh/Sections/Box.cpp \
    src/Mesh/Sections/Circle.cpp \
    src/Mesh/Sections/Generic.cpp \
    src/Mesh/Sections/I.cpp \
    src/Mesh/Sections/Rebar.cpp \
    src/Mesh/Sections/Rectangle.cpp \
    src/Mesh/Sections/Ring.cpp \
    src/Mesh/Sections/Section.cpp \
    src/Mesh/Sections/T.cpp \
    src/Models/Model.cpp \
    src/Plot/Colors.cpp \
    src/Plot/Gradient.cpp \
    src/Plot/Plot.cpp \
    src/Plot/Sizes.cpp \
    src/Plot/View.cpp \
    src/Plot/What.cpp \
    src/Topology/Curves/Curve.cpp \
    src/Topology/Curves/Line.cpp \
    src/Topology/Points/Point.cpp \
    src/Topology/Surfaces/Surface.cpp \
    src/Topology/Topology.cpp \


TARGET = fea
TEMPLATE = lib
CONFIG += staticlib
