include(../shared.pri)

HEADERS = \
    inc/benchmarks/heat/heat.h \
    inc/benchmarks/benchmarks.h \
    inc/benchmarks/material/material.h \
    inc/benchmarks/dof/dof.h \
    inc/benchmarks/mechanic/cable.h \
    inc/benchmarks/mechanic/deployable.h \
    inc/benchmarks/mechanic/joints.h \
    inc/benchmarks/mechanic/bar.h \
    inc/benchmarks/mechanic/beam.h \
    inc/benchmarks/mechanic/tensegrity.h \
    inc/benchmarks/mechanic/solid.h \
    inc/benchmarks/mechanic/plane.h \
    inc/equations/projectile.h \
    inc/equations/tent.h \
    inc/equations/gravity.h \
    inc/equations/electromag.h \
    inc/equations/equations.h \
    inc/equations/pendulum.h \


SOURCES = \
    src/benchmarks/heat/static/linear/plate.cpp \
    src/benchmarks/material/uniaxial/concrete/compression.cpp \
    src/benchmarks/material/uniaxial/concrete/tension.cpp \
    src/benchmarks/material/uniaxial/steel/steel.cpp \
    src/benchmarks/dof/buckling.cpp \
    src/benchmarks/dof/static_nonlinear.cpp \
    src/benchmarks/dof/static_linear.cpp \
    src/benchmarks/dof/modal.cpp \
    src/benchmarks/dof/supports.cpp \
    src/benchmarks/dof/dynamic_nonlinear.cpp \
    src/benchmarks/dof/dynamic_linear.cpp \
    src/benchmarks/dof/dependencies.cpp \
    src/benchmarks/mechanic/cable/buckling/cable.cpp \
    src/benchmarks/mechanic/cable/buckling/mixed.cpp \
    src/benchmarks/mechanic/cable/buckling/tower.cpp \
    src/benchmarks/mechanic/cable/dynamic/nonlinear/grid_weight.cpp \
    src/benchmarks/mechanic/cable/dynamic/nonlinear/line_bridge.cpp \
    src/benchmarks/mechanic/cable/dynamic/nonlinear/line_weight.cpp \
    src/benchmarks/mechanic/cable/modal/cable.cpp \
    src/benchmarks/mechanic/cable/modal/mixed.cpp \
    src/benchmarks/mechanic/cable/modal/tower.cpp \
    src/benchmarks/mechanic/cable/static/nonlinear/line_bridge.cpp \
    src/benchmarks/mechanic/joints/rigid/spring.cpp \
    src/benchmarks/mechanic/joints/rigid/motion.cpp \
    src/benchmarks/mechanic/joints/pinned/frame.cpp \
    src/benchmarks/mechanic/joints/pinned/cantilever.cpp \
    src/benchmarks/mechanic/joints/pinned/scissor.cpp \
    src/benchmarks/mechanic/joints/pinned/multi_scissor.cpp \
    src/benchmarks/mechanic/joints/pinned/shear.cpp \
    src/benchmarks/mechanic/joints/pinned/torsion.cpp \
    src/benchmarks/mechanic/joints/hinge/cantilever.cpp \
    src/benchmarks/mechanic/joints/hinge/axial.cpp \
    src/benchmarks/mechanic/joints/hinge/two_beams_axial.cpp \
    src/benchmarks/mechanic/joints/hinge/shear.cpp \
    src/benchmarks/mechanic/joints/hinge/torsion.cpp \
    src/benchmarks/mechanic/joints/hinge/bending.cpp \
    src/benchmarks/mechanic/joints/hinge/two_beams_torsion.cpp \
    src/benchmarks/mechanic/solid/static/linear/hinge.cpp \
    src/benchmarks/mechanic/solid/static/linear/axial.cpp \
    src/benchmarks/mechanic/beam/dynamic/nonlinear/pinned_free.cpp \
    src/benchmarks/mechanic/beam/dynamic/nonlinear/arc_shallow_clamped.cpp \
    src/benchmarks/mechanic/beam/dynamic/nonlinear/blade_rotation.cpp \
    src/benchmarks/mechanic/beam/dynamic/nonlinear/frame_lee.cpp \
    src/benchmarks/mechanic/beam/dynamic/nonlinear/cantilever_tip_force.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/elastic/arc_cantilever.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/elastic/arc_shallow_clamped.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/elastic/frame_roof.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/elastic/self_weight.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/elastic/arc_circle.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/elastic/column_buckling.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/elastic/frame_williams.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/elastic/cantilever_right_angle.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/elastic/frame_square.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/elastic/arc_asymmetric.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/elastic/cantilever_tip_moment.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/elastic/von_mises_buckling.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/elastic/frame_right_angle.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/elastic/frame_lee.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/elastic/hockling_cable.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/elastic/arc_shallow_pinned.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/elastic/frame_portal.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/elastic/cantilever_tip_force.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/inelastic/concrete/pinned_tip_moment.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/inelastic/concrete/column_buckling.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/inelastic/concrete/frame_square.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/inelastic/concrete/cantilever_tip_force.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/inelastic/steel/point_test_4.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/inelastic/steel/column_buckling.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/inelastic/steel/point_test_3.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/inelastic/steel/cantilever_tip_moment.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/inelastic/steel/propped_force_midspan.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/inelastic/steel/propped_force_distributed.cpp \
    src/benchmarks/mechanic/beam/static/nonlinear/inelastic/steel/cantilever_tip_force.cpp \
    src/benchmarks/mechanic/beam/static/linear/load_bending.cpp \
    src/benchmarks/mechanic/beam/static/linear/load_torsion.cpp \
    src/benchmarks/mechanic/beam/static/linear/load_axial.cpp \
    src/benchmarks/mechanic/beam/static/linear/load_shear.cpp \
    src/benchmarks/mechanic/beam/state/rigid_body.cpp \
    src/benchmarks/mechanic/beam/state/axial.cpp \
    src/benchmarks/mechanic/beam/state/shear.cpp \
    src/benchmarks/mechanic/beam/state/torsion.cpp \
    src/benchmarks/mechanic/beam/state/bending.cpp \
    src/benchmarks/mechanic/beam/buckling/column_buckling.cpp \
    src/benchmarks/mechanic/deployable/buckling/slut_unit.cpp \
    src/benchmarks/mechanic/deployable/static/nonlinear/arch_polar.cpp \
    src/benchmarks/mechanic/deployable/static/nonlinear/slut_beam.cpp \
    src/benchmarks/mechanic/deployable/static/nonlinear/tent_unit.cpp \
    src/benchmarks/mechanic/deployable/static/nonlinear/slut_test.cpp \
    src/benchmarks/mechanic/deployable/static/nonlinear/slut_line.cpp \
    src/benchmarks/mechanic/deployable/static/nonlinear/slut_unit.cpp \
    src/benchmarks/mechanic/deployable/static/nonlinear/arch_trans.cpp \
    src/benchmarks/mechanic/deployable/static/nonlinear/slut_roof.cpp \
    src/benchmarks/mechanic/deployable/static/nonlinear/tent_size.cpp \
    src/benchmarks/mechanic/deployable/static/nonlinear/slut_mult.cpp \
    src/benchmarks/mechanic/deployable/static/nonlinear/slut_fric.cpp \
    src/benchmarks/mechanic/deployable/static/nonlinear/slut_wall.cpp \
    src/benchmarks/mechanic/deployable/static/linear/arch_polar.cpp \
    src/benchmarks/mechanic/deployable/static/linear/arch_trans.cpp \
    src/benchmarks/mechanic/deployable/state/arch_polar.cpp \
    src/benchmarks/mechanic/deployable/state/slut_line.cpp \
    src/benchmarks/mechanic/deployable/state/slut_unit.cpp \
    src/benchmarks/mechanic/deployable/state/slut_roof.cpp \
    src/benchmarks/mechanic/deployable/state/slut_grid.cpp \
    src/benchmarks/mechanic/tensegrity/static/nonlinear/pentagon.cpp \
    src/benchmarks/mechanic/bar/dynamic/nonlinear/single_pendulum_3D.cpp \
    src/benchmarks/mechanic/bar/dynamic/nonlinear/tent_unit.cpp \
    src/benchmarks/mechanic/bar/dynamic/nonlinear/double_pendulum_2D.cpp \
    src/benchmarks/mechanic/bar/dynamic/nonlinear/single_pendulum_2D.cpp \
    src/benchmarks/mechanic/bar/dynamic/nonlinear/tent_roof.cpp \
    src/benchmarks/mechanic/bar/dynamic/linear/free.cpp \
    src/benchmarks/mechanic/bar/dynamic/linear/tent.cpp \
    src/benchmarks/mechanic/bar/static/nonlinear/cantilever.cpp \
    src/benchmarks/mechanic/bar/static/nonlinear/tower.cpp \
    src/benchmarks/mechanic/bar/static/nonlinear/von_mises_truss_2D.cpp \
    src/benchmarks/mechanic/bar/static/nonlinear/tent_unit.cpp \
    src/benchmarks/mechanic/bar/static/nonlinear/space_truss.cpp \
    src/benchmarks/mechanic/bar/static/nonlinear/pinned_tip_force.cpp \
    src/benchmarks/mechanic/bar/static/nonlinear/dome_star.cpp \
    src/benchmarks/mechanic/bar/static/nonlinear/von_mises_truss_3D.cpp \
    src/benchmarks/mechanic/bar/static/nonlinear/tent_roof.cpp \
    src/benchmarks/mechanic/bar/static/nonlinear/inelastic_tip_force.cpp \
    src/benchmarks/mechanic/bar/static/nonlinear/dome_circle.cpp \
    src/benchmarks/mechanic/bar/static/linear/load_point.cpp \
    src/benchmarks/mechanic/bar/static/linear/load_uniform.cpp \
    src/benchmarks/mechanic/bar/static/linear/truss_carol.cpp \
    src/benchmarks/mechanic/bar/modal/von_mises_truss_2D.cpp \
    src/benchmarks/mechanic/bar/buckling/single_bar.cpp \
    src/benchmarks/mechanic/bar/buckling/von_mises_truss_2D.cpp \
    src/benchmarks/mechanic/plane/static/linear/axial.cpp \
    src/equations/gravity.cpp \
    src/equations/projectile.cpp \
    src/equations/electromag.cpp \
    src/equations/tent.cpp \
    src/equations/pendulum.cpp \
    src/main.cpp \


TARGET = ben
TEMPLATE = app

LIBS += \
    -lfea \
    -lmat \
    -lboost_system \
    -lboost_filesystem \
    -lumfpack
